/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionListener;
import javax.security.auth.spi.LoginModule;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import tubespbo.Perpustakaan;

/**
 *
 * @author Indri's Property
 */
public class MenuPetugas extends javax.swing.JFrame {

    /**
     * Creates new form MenuPetugas
     */
    public MenuPetugas() {
        initComponents();
    }
    public JToggleButton getButtonTambahkanPinjaman(){
        return ButtonTambahkanPinjaman;
    }
    public JToggleButton getButtonKembalikanBuku(){
        return ButtonKembalikanBuku;
    }
    public JToggleButton getButtonUbahKondisi(){
        return ButtonUbahKondisi;
    }
    public JToggleButton getButtonTambahkanBukuPerpustakaan(){
        return ButtonTambahkanBukuPerpustakaan;
    }
    
    public JToggleButton getButtonMainMenu(){
        return ButtonMainMenu;
    }
    
    public void addListener(ActionListener e){
        ButtonTambahkanPinjaman.addActionListener(e);
        ButtonKembalikanBuku.addActionListener(e);
        ButtonUbahKondisi.addActionListener(e);
        ButtonTambahkanBukuPerpustakaan.addActionListener(e);
        ButtonMainMenu.addActionListener(e);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambahkanPinjaman = new javax.swing.JToggleButton();
        ButtonKembalikanBuku = new javax.swing.JToggleButton();
        ButtonUbahKondisi = new javax.swing.JToggleButton();
        ButtonTambahkanBukuPerpustakaan = new javax.swing.JToggleButton();
        ButtonMainMenu = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MENU PETUGAS");

        ButtonTambahkanPinjaman.setText("1. Tambahkan Pinjaman Anggota");

        ButtonKembalikanBuku.setText("2. Kembalikan Buku Pinjaman");

        ButtonUbahKondisi.setText("3. Ubah Kondisi Buku");

        ButtonTambahkanBukuPerpustakaan.setText("4. Tambahkan Buku Ke Perpustakaan");

        ButtonMainMenu.setText("5. Back To Main Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahkanBukuPerpustakaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonKembalikanBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonTambahkanPinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonUbahKondisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonTambahkanPinjaman)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembalikanBuku)
                .addGap(18, 18, 18)
                .addComponent(ButtonUbahKondisi)
                .addGap(18, 18, 18)
                .addComponent(ButtonTambahkanBukuPerpustakaan)
                .addGap(18, 18, 18)
                .addComponent(ButtonMainMenu)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonKembalikanBuku;
    private javax.swing.JToggleButton ButtonMainMenu;
    private javax.swing.JToggleButton ButtonTambahkanBukuPerpustakaan;
    private javax.swing.JToggleButton ButtonTambahkanPinjaman;
    private javax.swing.JToggleButton ButtonUbahKondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
