/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionListener;
import javax.security.auth.spi.LoginModule;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import tubespbo.Perpustakaan;


/**
 *
 * @author Indri's Property
 */
public class TambahBukuPerpus extends javax.swing.JFrame {

    /**
     * Creates new form TambahBukuPerpus
     */
    public TambahBukuPerpus() {
        initComponents();
    }
    
    public JButton getButtonBaik(){
        return ButtonBaik;
    }
    public JButton getButtonBuruk(){
        return ButtonBuruk;
    }
    public JButton getButtonTambahkanKePerpustakaan(){
        return ButtonTambahkankePerpustakaan;
    }
    public JButton getMenuPetugas(){
        return ButtonMenuPetugas;
    }
    
    public JTextField getIdBuku(){
        return tfIdBuku;
    }
    public JTextField getJudulBuku(){
        return tfJudulBuku;
    }
    public JTextField getPengarang(){
        return tfPengarang;
    }
    public String getIdBuku1(){
        return tfIdBuku.getText();
    }
    public String getJudulBuku1(){
        return tfJudulBuku.getText();
    }
    public String getPengarang1(){
        return tfPengarang.getText();
    }
    
    public void addListener(ActionListener e){
        ButtonBaik.addActionListener(e);
        ButtonBuruk.addActionListener(e);
        ButtonTambahkankePerpustakaan.addActionListener(e);
        ButtonMenuPetugas.addActionListener(e);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdBuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJudulBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPengarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButtonBaik = new javax.swing.JButton();
        ButtonBuruk = new javax.swing.JButton();
        ButtonTambahkankePerpustakaan = new javax.swing.JButton();
        ButtonMenuPetugas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tambah Buku Ke Perpustakaan");

        jLabel2.setText("Masukan ID Buku : ");

        jLabel3.setText("Judul Buku :");

        jLabel4.setText("Pengarang :");

        jLabel5.setText("Kondisi :");

        ButtonBaik.setText("Baik");

        ButtonBuruk.setText("Buruk");

        ButtonTambahkankePerpustakaan.setText("Tambahkan Ke Perpustakaan");

        ButtonMenuPetugas.setText("Back To Menu Petugas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonTambahkankePerpustakaan)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ButtonBaik)
                                    .addGap(18, 18, 18)
                                    .addComponent(ButtonBuruk))
                                .addComponent(tfJudulBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                .addComponent(tfIdBuku)
                                .addComponent(tfPengarang))))
                    .addComponent(ButtonMenuPetugas))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ButtonBuruk)
                    .addComponent(ButtonBaik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonTambahkankePerpustakaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(ButtonMenuPetugas)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBaik;
    private javax.swing.JButton ButtonBuruk;
    private javax.swing.JButton ButtonMenuPetugas;
    private javax.swing.JButton ButtonTambahkankePerpustakaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfIdBuku;
    private javax.swing.JTextField tfJudulBuku;
    private javax.swing.JTextField tfPengarang;
    // End of variables declaration//GEN-END:variables
}
